---
- hosts: devops_server
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes
